name: consul
services:
  consulinstallation:
    type: $(#use https://raw.githubusercontent.com/Zanda256/meshery-consul/add-e2e-tests/%23249/.github/install/installconsul.yaml)
    settings: 
        controlplaneNS: consul
        namespace: default
        consulVersion: 1.12.2
        profile: default
  hashicups:
    type: $(#use https://raw.githubusercontent.com/Zanda256/meshery-consul/add-e2e-tests/%23249/.github/install/hashiCupsPattern.yaml)
    dependsOn:
      - consulinstallation

